// Auth
const LOGIN_USER = 'LOGIN_USER';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';
const SEND_OTP = 'SEND_OTP';
const VERIFY_OTP = 'VERIFY_OTP';
const RESEND_OTP = 'RESEND_OTP';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const OTP_REQUEST_FAILED = 'OTP_REQUEST_FAILED';
const PASSWORD_REQUEST_FAILED = 'PASSWORD_REQUEST_FAILED';

// Tutor
const GET_TUTOR_LIST = 'GET_TUTOR_LIST';
const REGISTER_TUTOR_COACH = 'REGISTER_TUTOR_COACH';
const GET_TUTOR_ACCOUNT = 'GET_TUTOR_ACCOUNT';
const GET_TUTOR_DETAIL = 'GET_TUTOR_DETAIL';
const UPDATE_TUTOR_ACCOUNT = 'UPDATE_TUTOR_ACCOUNT';
const SAVE_BANK_DETAIL = 'SAVE_BANK_DETAIL';
const GET_BANK_DETAIL = 'GET_BANK_DETAIL';
const SAVE_TUTOR_SCHEDULE = 'SAVE_TUTOR_SCHEDULE';
const GET_TUTOR_SCHEDULE = 'GET_TUTOR_SCHEDULE';
const SAVE_TUTOR_SUBJECT = 'SAVE_TUTOR_SUBJECT';
const SAVE_REQUESTED_SUBJECT = 'SAVE_REQUESTED_SUBJECT';
const GET_TUTOR_SUBJECTS = 'GET_TUTOR_SUBJECTS';
const UPDATE_SUBJECT_LANGUAGE = 'UPDATE_SUBJECT_LANGUAGE';
const DELETE_SUBJECT = 'DELETE_SUBJECT';
const TUTOR_COACH_REQUEST_FAILED = 'TUTOR_COACH_REQUEST_FAILED';

// Student
const REGISTER_STUDENT_USER = 'REGISTER_STUDENT_USER';
const STUDENT_USER_REQUEST_FAILED = 'STUDENT_USER_REQUEST_FAILED';

// Setup
const COUNTRY_CODES = 'COUNTRY_CODES';
const SEARCH_COUNTRY_CODES = 'SEARCH_COUNTRY_CODES';
const DONE_WALKTHROUGH = 'DONE_WALKTHROUGH';
const CHECK_WALKTHROUGH = 'CHECK_WALKTHROUGH';
const SETUP_REQUEST_FAILED = 'SETUP_REQUEST_FAILED';

// App local flow
const SETUP_BOOKING = 'SETUP_BOOKING';
const APP_LOCAL_FAILED = 'APP_LOCAL_FAILED';

export {
  // Auth
  LOGIN_USER,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT,
  CHANGE_PASSWORD,
  SEND_OTP,
  VERIFY_OTP,
  RESEND_OTP,
  OTP_REQUEST_FAILED,
  PASSWORD_REQUEST_FAILED,
  // Tutor
  GET_TUTOR_LIST,
  REGISTER_TUTOR_COACH,
  GET_TUTOR_ACCOUNT,
  GET_TUTOR_DETAIL,
  UPDATE_TUTOR_ACCOUNT,
  SAVE_BANK_DETAIL,
  GET_BANK_DETAIL,
  SAVE_TUTOR_SCHEDULE,
  GET_TUTOR_SCHEDULE,
  SAVE_TUTOR_SUBJECT,
  SAVE_REQUESTED_SUBJECT,
  GET_TUTOR_SUBJECTS,
  UPDATE_SUBJECT_LANGUAGE,
  DELETE_SUBJECT,
  TUTOR_COACH_REQUEST_FAILED,
  // Student
  REGISTER_STUDENT_USER,
  STUDENT_USER_REQUEST_FAILED,
  // Setup
  COUNTRY_CODES,
  SEARCH_COUNTRY_CODES,
  DONE_WALKTHROUGH,
  CHECK_WALKTHROUGH,
  SETUP_REQUEST_FAILED,
  // APP LOCAL
  SETUP_BOOKING,
  APP_LOCAL_FAILED,
};
